name: Continous Integration (CI)

## Run CI jobs on all branches on deffault
on:
  push:
    pull_request:

jobs:
  test:
    name: Run test
    runs-on: ubuntu-22.04
    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v4
      - name: Set up java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"
      - name: Set gradlew as executable
        run: chmod +x ./gradlew
      - name: Run unit tests
        run: ./gradlew test
